name: Run gulp tasks

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install gulp
        run: |
          npm ci
          npm install -g gulp

      - name: Run gulp
        run: gulp

      - name: Clean files after gulp
        run: |
          rm -rf node_modules/
          mv dist/* ./
          rm -rf dist

      - name: Get favicon
        run: |
          apt-get install wget
          sudo wget https://avatars.githubusercontent.com/awakair -O favicon.ico

      - name: Commit files
        run: |
          git config --local user.name  ${{ github.actor }}
          git checkout -b gh-pages
          git add -A
          git commit -m "Update gulp output files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
